Add database
julia-gerasimenko/java-filmorate pull request #6
Opened 2023-06-22 11:09 UTC by julia-gerasimenko

Привет! Результат моих мучений, посмотри, пожалуйста.

2023-06-22 11:58 UTC, EugeneLenkevich requested changes
Привет, Юлия, спасибо за PR

Здорово! У меня только косметические пометки, ничего серьезного. обрати внимание еше на то как Optional-ом пользуешься, можно проще, отметил небольшим коментарием

Ну и тесты вроде как не проходят, посмотри, пожалуйста :)

2023-06-22 11:58 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      public Film createFilm(Film film) {
Сервис называется FilmService 
метод
public Film createFilm(Film film)

в принципе понятно что он работает с фильмами. А что если вот так назвать, покороче и, вроде, так же все понятно :)
public Film create (Film film)

2023-06-22 11:58 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementations/GenreDaoImpl.java
> +        if (genre.size() == 0)
{} тоже бы не забывать даже если далее всего один оператор, читать код проще :)

2023-06-22 11:58 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        genreDao.updateFilmGenre(film);
Думаю тут можно организовать распределение обязанностей немного по другому - опустить genreDao.updateFilmGenre(film) на уровень хранилища, это же по сути своей вспомогательная связь, а не объект бизнес-логики, получается что смешиваем технические детали хранения дланных и логику доменную логику. Что думаешь?

2023-06-22 11:58 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +        Optional<Genre> genre = genreDao.getGenreById(id);
Genre genre = genreDao.getGenreById(id).orElseThrow(->  throw new NotFoundException("Жанр с id {} не был найден" + id));

Вот так покороче можно записать :)

2023-06-22 11:58 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/implementations/FilmDaoImpl.java
> +        if (count == 0)
if(...) {
 одинОператор();
}  
Стиль все же стоит соблюсти :)

2023-06-23 11:09 UTC, julia-gerasimenko commented
Ура, я прошла все тесты, это было сложно)))

2023-06-23 11:17 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-06-25 05:44 UTC, merged